### ISSUE TITLE
Documentation/Wiki?

### ISSUE THREAD

**Issue by a10y** [grt192/grtframework#1]
This code seems to be functioning to desired purpose. When we feel it's good enough, some more explicit form of docs beyond javadoc should be added. Github has project wikis, so that might be the best option.

**Comment by a10y** [comment]
I'm too old for this shit

**Comment by frei0** [comment]
wow u gave me a notification when im supposed to be studying now u get one back haha

**Comment by a10y** [comment]
@dannyperson @dannyperson 

# You suck

**Comment by frei0** [comment]
jokes on you i wasnt studying anyway
